=== OfflineBrain/hex-rl/src/commonMain/resources/generation/schema/genrules.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://com.offlinebrain/schema/hexrl/genrules.schema.json",
  "title": "Constraint",
  "description": "A constraint on a transformation.",
  "type": "object",
  "properties": {
    "size": {
      "type": "object",
      "$ref": "room_size.schema.json"
    },
    "generations": {
      "type": "integer",
      "minimum": 1
    },
    "initialStates": {
      "type": "object",
      "propertyNames": {
        "$ref": "cell.schema.json"
      },
      "patternProperties": {
        "": {
          "type": "number",
          "minimum": 0,
          "maximum": 1
        }
      },
      "additionalProperties": false,
      "minProperties": 1
    },
    "rules": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "states": {
            "type": "array",
            "items": {
              "$ref": "cell.schema.json"
            },
            "minItems": 1
          },
          "transformations": {
            "type": "array",
            "items": {
              "$ref": "transformation_rule.schema.json"
            },
            "minItems": 1
          }
        },
        "additionalProperties": false,
        "required": [
          "states",
          "transformations"
        ]
      },
      "minItems": 1
    },
    "goal": {
      "type": "object",
      "properties": {
        "match": {
          "$ref": "match.schema.json"
        },
        "constraints": {
          "type": "array",
          "items": {
            "$ref": "constraint.schema.json"
          },
          "minItems": 1
        }
      },
      "required": [
        "constraints",
        "match"
      ],
      "additionalProperties": false
    }
  },
  "additionalProperties": false,
  "required": [
    "generations",
    "initialStates",
    "rules",
    "size",
    "goal"
  ]
}

=== OfflineBrain/hex-rl/src/commonMain/resources/generation/data/bigBlobRoomGenRules.json
{
  "size": {
    "minWidth": 10,
    "minHeight": 10,
    "maxWidth": 25,
    "maxHeight": 25
  },
  "generations": 5,
  "initialStates": {
    "FLOOR": 0.5,
    "WALL": 0.5
  },
  "rules": [
    {
      "states": [
        "FLOOR"
      ],
      "transformations": [
        {
          "match": "ALL",
          "constraints": [
            {
              "cell": "WALL",
              "value": 3,
              "condition": {
                "#operator": ">="
              }
            },
            {
              "cell": "WALL",
              "value": 5,
              "condition": {
                "#operator": "!="
              }
            }
          ],
          "result": "WALL"
        },
        {
          "match": "ALL",
          "constraints": [
            {
              "cell": "WALL",
              "value": 5,
              "condition": {
                "#operator": "=="
              }
            }
          ],
          "result": "LIGHT_CRYSTAL"
        }
      ]
    },
    {
      "states": [
        "WALL"
      ],
      "transformations": [
        {
          "match": "ALL",
          "constraints": [
            {
              "cell": "FLOOR",
              "value": 3,
              "condition": {
                "#operator": ">="
              }
            },
            {
              "cell": "FLOOR",
              "value": 6,
              "condition": {
                "#operator": "<="
              }
            }
          ],
          "result": "FLOOR",
          "probability": 0.5
        },
        {
          "match": "ALL",
          "constraints": [
            {
              "cell": "FLOOR",
              "value": 6,
              "condition": {
                "#operator": "=="
              }
            }
          ],
          "result": "LIGHT_CRYSTAL",
          "probability": 0.5
        }
      ]
    }
  ],
  "goal": {
    "match": "ALL",
    "constraints": [
      {
        "cell": "FLOOR",
        "value": 10,
        "condition": {
          "#operator": ">="
        }
      }
    ]
  }
}

=== OfflineBrain/hex-rl/src/commonMain/resources/generation/data/bigRoomsConfig.json
{
  "size": {
    "minWidth": 20,
    "minHeight": 20,
    "maxWidth": 25,
    "maxHeight": 25
  },
  "generations": 5,
  "initialStates": {
    "FLOOR": 0.5,
    "WALL": 0.5
  },
  "rules": [
    {
      "states": [
        "LIGHT_CRYSTAL"
      ],
      "transformations": [
        {
          "match": "ALL",
          "result": "FLOOR",
          "probability": 1,
          "constraints": [
            {
              "value": 1,
              "cell": "LIGHT_CRYSTAL",
              "condition": {
                "#operator": ">="
              }
            }
          ]
        }
      ]
    },
    {
      "states": [
        "FLOOR"
      ],
      "transformations": [
        {
          "match": "ALL",
          "constraints": [
            {
              "cell": "WALL",
              "value": 4,
              "condition": {
                "#operator": ">="
              }
            },
            {
              "cell": "WALL",
              "value": 5,
              "condition": {
                "#operator": "!="
              }
            }
          ],
          "result": "WALL"
        }
      ]
    },
    {
      "states": [
        "WALL"
      ],
      "transformations": [
        {
          "match": "ALL",
          "constraints": [
            {
              "cell": "FLOOR",
              "value": 4,
              "condition": {
                "#operator": ">="
              }
            },
            {
              "cell": "FLOOR",
              "value": 6,
              "condition": {
                "#operator": "<"
              }
            }
          ],
          "result": "FLOOR",
          "probability": 1
        }
      ]
    }
  ],
  "goal": {
    "match": "ALL",
    "constraints": [
      {
        "cell": "FLOOR",
        "value": 10,
        "condition": {
          "#operator": ">="
        }
      }
    ]
  }
}
